server:
  port: 8080
logging:
  level:
    org.springframework.jdbc.core: TRACE
spring:
  sql:
    init:
      mode: always
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/sns?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=99999&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false
springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
